
public class AssingmentsAndStrings {
    
    public static void main(String[] args) {
    	// = us used as a assingment operator
    	int num1 = 10; // Declaration and Initialization
    	int num2 = 5;
 
    	 int sum = num1 + num2; 
    	 	
    	 System.out.println("The sum of num 1 and sum 2 is " + sum);
    	   
    	 
    	 int a = 5;
    	 int b = 3;
    	 
    	 int result = 0; // Declaration and Initialization
    	 result += a; // result = result + a;
    	 result -= b; // result = result - b; 
    	 
    	 //System.out.println(result);
    	 
    	//strings are sequence of chars
    	//enclosed in double quotes " " 
    	 String firstname = "Renz";
    	 String lastname = "Gabun";
    	 
    	 
    	 //concatenation - combining of using '+'
    	 String Fullname = firstname + " " + lastname;
    	 
    	 System.out.println(Fullname);
    	 
    }
}
